// Code generated by ent, DO NOT EDIT.

package productprice

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the productprice type in the database.
	Label = "product_price"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModificationDate holds the string denoting the modification_date field in the database.
	FieldModificationDate = "modification_date"
	// FieldNewPrice holds the string denoting the new_price field in the database.
	FieldNewPrice = "new_price"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "product"
	// Table holds the table name of the productprice in the database.
	Table = "product_prices"
	// ProductTable is the table that holds the product relation/edge.
	ProductTable = "product_prices"
	// ProductInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	ProductInverseTable = "products"
	// ProductColumn is the table column denoting the product relation/edge.
	ProductColumn = "product_id"
)

// Columns holds all SQL columns for productprice fields.
var Columns = []string{
	FieldID,
	FieldModificationDate,
	FieldNewPrice,
	FieldProductID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ProductPrice queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModificationDate orders the results by the modification_date field.
func ByModificationDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModificationDate, opts...).ToFunc()
}

// ByNewPrice orders the results by the new_price field.
func ByNewPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewPrice, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByProductField orders the results by product field.
func ByProductField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductStep(), sql.OrderByField(field, opts...))
	}
}
func newProductStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
	)
}
