// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/db/ent/address"
	"main/db/ent/order"
	"main/db/ent/predicate"
	"main/db/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AddressUpdate is the builder for updating Address entities.
type AddressUpdate struct {
	config
	hooks    []Hook
	mutation *AddressMutation
}

// Where appends a list predicates to the AddressUpdate builder.
func (au *AddressUpdate) Where(ps ...predicate.Address) *AddressUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetCity sets the "city" field.
func (au *AddressUpdate) SetCity(s string) *AddressUpdate {
	au.mutation.SetCity(s)
	return au
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (au *AddressUpdate) SetNillableCity(s *string) *AddressUpdate {
	if s != nil {
		au.SetCity(*s)
	}
	return au
}

// ClearCity clears the value of the "city" field.
func (au *AddressUpdate) ClearCity() *AddressUpdate {
	au.mutation.ClearCity()
	return au
}

// SetStreetName sets the "street_name" field.
func (au *AddressUpdate) SetStreetName(s string) *AddressUpdate {
	au.mutation.SetStreetName(s)
	return au
}

// SetNillableStreetName sets the "street_name" field if the given value is not nil.
func (au *AddressUpdate) SetNillableStreetName(s *string) *AddressUpdate {
	if s != nil {
		au.SetStreetName(*s)
	}
	return au
}

// ClearStreetName clears the value of the "street_name" field.
func (au *AddressUpdate) ClearStreetName() *AddressUpdate {
	au.mutation.ClearStreetName()
	return au
}

// SetHouseNumber sets the "house_number" field.
func (au *AddressUpdate) SetHouseNumber(s string) *AddressUpdate {
	au.mutation.SetHouseNumber(s)
	return au
}

// SetNillableHouseNumber sets the "house_number" field if the given value is not nil.
func (au *AddressUpdate) SetNillableHouseNumber(s *string) *AddressUpdate {
	if s != nil {
		au.SetHouseNumber(*s)
	}
	return au
}

// ClearHouseNumber clears the value of the "house_number" field.
func (au *AddressUpdate) ClearHouseNumber() *AddressUpdate {
	au.mutation.ClearHouseNumber()
	return au
}

// SetStoreName sets the "store_name" field.
func (au *AddressUpdate) SetStoreName(s string) *AddressUpdate {
	au.mutation.SetStoreName(s)
	return au
}

// SetNillableStoreName sets the "store_name" field if the given value is not nil.
func (au *AddressUpdate) SetNillableStoreName(s *string) *AddressUpdate {
	if s != nil {
		au.SetStoreName(*s)
	}
	return au
}

// ClearStoreName clears the value of the "store_name" field.
func (au *AddressUpdate) ClearStoreName() *AddressUpdate {
	au.mutation.ClearStoreName()
	return au
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (au *AddressUpdate) AddUserIDs(ids ...int) *AddressUpdate {
	au.mutation.AddUserIDs(ids...)
	return au
}

// AddUser adds the "user" edges to the User entity.
func (au *AddressUpdate) AddUser(u ...*User) *AddressUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return au.AddUserIDs(ids...)
}

// AddAddresIDs adds the "address" edge to the Order entity by IDs.
func (au *AddressUpdate) AddAddresIDs(ids ...int) *AddressUpdate {
	au.mutation.AddAddresIDs(ids...)
	return au
}

// AddAddress adds the "address" edges to the Order entity.
func (au *AddressUpdate) AddAddress(o ...*Order) *AddressUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return au.AddAddresIDs(ids...)
}

// Mutation returns the AddressMutation object of the builder.
func (au *AddressUpdate) Mutation() *AddressMutation {
	return au.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (au *AddressUpdate) ClearUser() *AddressUpdate {
	au.mutation.ClearUser()
	return au
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (au *AddressUpdate) RemoveUserIDs(ids ...int) *AddressUpdate {
	au.mutation.RemoveUserIDs(ids...)
	return au
}

// RemoveUser removes "user" edges to User entities.
func (au *AddressUpdate) RemoveUser(u ...*User) *AddressUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return au.RemoveUserIDs(ids...)
}

// ClearAddress clears all "address" edges to the Order entity.
func (au *AddressUpdate) ClearAddress() *AddressUpdate {
	au.mutation.ClearAddress()
	return au
}

// RemoveAddresIDs removes the "address" edge to Order entities by IDs.
func (au *AddressUpdate) RemoveAddresIDs(ids ...int) *AddressUpdate {
	au.mutation.RemoveAddresIDs(ids...)
	return au
}

// RemoveAddress removes "address" edges to Order entities.
func (au *AddressUpdate) RemoveAddress(o ...*Order) *AddressUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return au.RemoveAddresIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AddressUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AddressUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AddressUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AddressUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AddressUpdate) check() error {
	if v, ok := au.mutation.City(); ok {
		if err := address.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Address.city": %w`, err)}
		}
	}
	if v, ok := au.mutation.StreetName(); ok {
		if err := address.StreetNameValidator(v); err != nil {
			return &ValidationError{Name: "street_name", err: fmt.Errorf(`ent: validator failed for field "Address.street_name": %w`, err)}
		}
	}
	if v, ok := au.mutation.HouseNumber(); ok {
		if err := address.HouseNumberValidator(v); err != nil {
			return &ValidationError{Name: "house_number", err: fmt.Errorf(`ent: validator failed for field "Address.house_number": %w`, err)}
		}
	}
	if v, ok := au.mutation.StoreName(); ok {
		if err := address.StoreNameValidator(v); err != nil {
			return &ValidationError{Name: "store_name", err: fmt.Errorf(`ent: validator failed for field "Address.store_name": %w`, err)}
		}
	}
	return nil
}

func (au *AddressUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.City(); ok {
		_spec.SetField(address.FieldCity, field.TypeString, value)
	}
	if au.mutation.CityCleared() {
		_spec.ClearField(address.FieldCity, field.TypeString)
	}
	if value, ok := au.mutation.StreetName(); ok {
		_spec.SetField(address.FieldStreetName, field.TypeString, value)
	}
	if au.mutation.StreetNameCleared() {
		_spec.ClearField(address.FieldStreetName, field.TypeString)
	}
	if value, ok := au.mutation.HouseNumber(); ok {
		_spec.SetField(address.FieldHouseNumber, field.TypeString, value)
	}
	if au.mutation.HouseNumberCleared() {
		_spec.ClearField(address.FieldHouseNumber, field.TypeString)
	}
	if value, ok := au.mutation.StoreName(); ok {
		_spec.SetField(address.FieldStoreName, field.TypeString, value)
	}
	if au.mutation.StoreNameCleared() {
		_spec.ClearField(address.FieldStoreName, field.TypeString)
	}
	if au.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   address.UserTable,
			Columns: address.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedUserIDs(); len(nodes) > 0 && !au.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   address.UserTable,
			Columns: address.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   address.UserTable,
			Columns: address.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.AddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   address.AddressTable,
			Columns: []string{address.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedAddressIDs(); len(nodes) > 0 && !au.mutation.AddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   address.AddressTable,
			Columns: []string{address.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.AddressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   address.AddressTable,
			Columns: []string{address.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AddressUpdateOne is the builder for updating a single Address entity.
type AddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AddressMutation
}

// SetCity sets the "city" field.
func (auo *AddressUpdateOne) SetCity(s string) *AddressUpdateOne {
	auo.mutation.SetCity(s)
	return auo
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (auo *AddressUpdateOne) SetNillableCity(s *string) *AddressUpdateOne {
	if s != nil {
		auo.SetCity(*s)
	}
	return auo
}

// ClearCity clears the value of the "city" field.
func (auo *AddressUpdateOne) ClearCity() *AddressUpdateOne {
	auo.mutation.ClearCity()
	return auo
}

// SetStreetName sets the "street_name" field.
func (auo *AddressUpdateOne) SetStreetName(s string) *AddressUpdateOne {
	auo.mutation.SetStreetName(s)
	return auo
}

// SetNillableStreetName sets the "street_name" field if the given value is not nil.
func (auo *AddressUpdateOne) SetNillableStreetName(s *string) *AddressUpdateOne {
	if s != nil {
		auo.SetStreetName(*s)
	}
	return auo
}

// ClearStreetName clears the value of the "street_name" field.
func (auo *AddressUpdateOne) ClearStreetName() *AddressUpdateOne {
	auo.mutation.ClearStreetName()
	return auo
}

// SetHouseNumber sets the "house_number" field.
func (auo *AddressUpdateOne) SetHouseNumber(s string) *AddressUpdateOne {
	auo.mutation.SetHouseNumber(s)
	return auo
}

// SetNillableHouseNumber sets the "house_number" field if the given value is not nil.
func (auo *AddressUpdateOne) SetNillableHouseNumber(s *string) *AddressUpdateOne {
	if s != nil {
		auo.SetHouseNumber(*s)
	}
	return auo
}

// ClearHouseNumber clears the value of the "house_number" field.
func (auo *AddressUpdateOne) ClearHouseNumber() *AddressUpdateOne {
	auo.mutation.ClearHouseNumber()
	return auo
}

// SetStoreName sets the "store_name" field.
func (auo *AddressUpdateOne) SetStoreName(s string) *AddressUpdateOne {
	auo.mutation.SetStoreName(s)
	return auo
}

// SetNillableStoreName sets the "store_name" field if the given value is not nil.
func (auo *AddressUpdateOne) SetNillableStoreName(s *string) *AddressUpdateOne {
	if s != nil {
		auo.SetStoreName(*s)
	}
	return auo
}

// ClearStoreName clears the value of the "store_name" field.
func (auo *AddressUpdateOne) ClearStoreName() *AddressUpdateOne {
	auo.mutation.ClearStoreName()
	return auo
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (auo *AddressUpdateOne) AddUserIDs(ids ...int) *AddressUpdateOne {
	auo.mutation.AddUserIDs(ids...)
	return auo
}

// AddUser adds the "user" edges to the User entity.
func (auo *AddressUpdateOne) AddUser(u ...*User) *AddressUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return auo.AddUserIDs(ids...)
}

// AddAddresIDs adds the "address" edge to the Order entity by IDs.
func (auo *AddressUpdateOne) AddAddresIDs(ids ...int) *AddressUpdateOne {
	auo.mutation.AddAddresIDs(ids...)
	return auo
}

// AddAddress adds the "address" edges to the Order entity.
func (auo *AddressUpdateOne) AddAddress(o ...*Order) *AddressUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return auo.AddAddresIDs(ids...)
}

// Mutation returns the AddressMutation object of the builder.
func (auo *AddressUpdateOne) Mutation() *AddressMutation {
	return auo.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (auo *AddressUpdateOne) ClearUser() *AddressUpdateOne {
	auo.mutation.ClearUser()
	return auo
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (auo *AddressUpdateOne) RemoveUserIDs(ids ...int) *AddressUpdateOne {
	auo.mutation.RemoveUserIDs(ids...)
	return auo
}

// RemoveUser removes "user" edges to User entities.
func (auo *AddressUpdateOne) RemoveUser(u ...*User) *AddressUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return auo.RemoveUserIDs(ids...)
}

// ClearAddress clears all "address" edges to the Order entity.
func (auo *AddressUpdateOne) ClearAddress() *AddressUpdateOne {
	auo.mutation.ClearAddress()
	return auo
}

// RemoveAddresIDs removes the "address" edge to Order entities by IDs.
func (auo *AddressUpdateOne) RemoveAddresIDs(ids ...int) *AddressUpdateOne {
	auo.mutation.RemoveAddresIDs(ids...)
	return auo
}

// RemoveAddress removes "address" edges to Order entities.
func (auo *AddressUpdateOne) RemoveAddress(o ...*Order) *AddressUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return auo.RemoveAddresIDs(ids...)
}

// Where appends a list predicates to the AddressUpdate builder.
func (auo *AddressUpdateOne) Where(ps ...predicate.Address) *AddressUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AddressUpdateOne) Select(field string, fields ...string) *AddressUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Address entity.
func (auo *AddressUpdateOne) Save(ctx context.Context) (*Address, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AddressUpdateOne) SaveX(ctx context.Context) *Address {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AddressUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AddressUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AddressUpdateOne) check() error {
	if v, ok := auo.mutation.City(); ok {
		if err := address.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Address.city": %w`, err)}
		}
	}
	if v, ok := auo.mutation.StreetName(); ok {
		if err := address.StreetNameValidator(v); err != nil {
			return &ValidationError{Name: "street_name", err: fmt.Errorf(`ent: validator failed for field "Address.street_name": %w`, err)}
		}
	}
	if v, ok := auo.mutation.HouseNumber(); ok {
		if err := address.HouseNumberValidator(v); err != nil {
			return &ValidationError{Name: "house_number", err: fmt.Errorf(`ent: validator failed for field "Address.house_number": %w`, err)}
		}
	}
	if v, ok := auo.mutation.StoreName(); ok {
		if err := address.StoreNameValidator(v); err != nil {
			return &ValidationError{Name: "store_name", err: fmt.Errorf(`ent: validator failed for field "Address.store_name": %w`, err)}
		}
	}
	return nil
}

func (auo *AddressUpdateOne) sqlSave(ctx context.Context) (_node *Address, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Address.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, address.FieldID)
		for _, f := range fields {
			if !address.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != address.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.City(); ok {
		_spec.SetField(address.FieldCity, field.TypeString, value)
	}
	if auo.mutation.CityCleared() {
		_spec.ClearField(address.FieldCity, field.TypeString)
	}
	if value, ok := auo.mutation.StreetName(); ok {
		_spec.SetField(address.FieldStreetName, field.TypeString, value)
	}
	if auo.mutation.StreetNameCleared() {
		_spec.ClearField(address.FieldStreetName, field.TypeString)
	}
	if value, ok := auo.mutation.HouseNumber(); ok {
		_spec.SetField(address.FieldHouseNumber, field.TypeString, value)
	}
	if auo.mutation.HouseNumberCleared() {
		_spec.ClearField(address.FieldHouseNumber, field.TypeString)
	}
	if value, ok := auo.mutation.StoreName(); ok {
		_spec.SetField(address.FieldStoreName, field.TypeString, value)
	}
	if auo.mutation.StoreNameCleared() {
		_spec.ClearField(address.FieldStoreName, field.TypeString)
	}
	if auo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   address.UserTable,
			Columns: address.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedUserIDs(); len(nodes) > 0 && !auo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   address.UserTable,
			Columns: address.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   address.UserTable,
			Columns: address.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.AddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   address.AddressTable,
			Columns: []string{address.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedAddressIDs(); len(nodes) > 0 && !auo.mutation.AddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   address.AddressTable,
			Columns: []string{address.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.AddressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   address.AddressTable,
			Columns: []string{address.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Address{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
