// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"main/db/ent/order"
	"main/db/ent/orderdetail"
	"main/db/ent/product"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderDetailCreate is the builder for creating a OrderDetail entity.
type OrderDetailCreate struct {
	config
	mutation *OrderDetailMutation
	hooks    []Hook
}

// SetQuantity sets the "quantity" field.
func (odc *OrderDetailCreate) SetQuantity(i int) *OrderDetailCreate {
	odc.mutation.SetQuantity(i)
	return odc
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (odc *OrderDetailCreate) SetNillableQuantity(i *int) *OrderDetailCreate {
	if i != nil {
		odc.SetQuantity(*i)
	}
	return odc
}

// SetOrderID sets the "order_id" field.
func (odc *OrderDetailCreate) SetOrderID(i int) *OrderDetailCreate {
	odc.mutation.SetOrderID(i)
	return odc
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (odc *OrderDetailCreate) SetNillableOrderID(i *int) *OrderDetailCreate {
	if i != nil {
		odc.SetOrderID(*i)
	}
	return odc
}

// SetProductID sets the "product_id" field.
func (odc *OrderDetailCreate) SetProductID(i int) *OrderDetailCreate {
	odc.mutation.SetProductID(i)
	return odc
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (odc *OrderDetailCreate) SetNillableProductID(i *int) *OrderDetailCreate {
	if i != nil {
		odc.SetProductID(*i)
	}
	return odc
}

// SetOrder sets the "order" edge to the Order entity.
func (odc *OrderDetailCreate) SetOrder(o *Order) *OrderDetailCreate {
	return odc.SetOrderID(o.ID)
}

// SetProductsID sets the "products" edge to the Product entity by ID.
func (odc *OrderDetailCreate) SetProductsID(id int) *OrderDetailCreate {
	odc.mutation.SetProductsID(id)
	return odc
}

// SetNillableProductsID sets the "products" edge to the Product entity by ID if the given value is not nil.
func (odc *OrderDetailCreate) SetNillableProductsID(id *int) *OrderDetailCreate {
	if id != nil {
		odc = odc.SetProductsID(*id)
	}
	return odc
}

// SetProducts sets the "products" edge to the Product entity.
func (odc *OrderDetailCreate) SetProducts(p *Product) *OrderDetailCreate {
	return odc.SetProductsID(p.ID)
}

// Mutation returns the OrderDetailMutation object of the builder.
func (odc *OrderDetailCreate) Mutation() *OrderDetailMutation {
	return odc.mutation
}

// Save creates the OrderDetail in the database.
func (odc *OrderDetailCreate) Save(ctx context.Context) (*OrderDetail, error) {
	return withHooks(ctx, odc.sqlSave, odc.mutation, odc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (odc *OrderDetailCreate) SaveX(ctx context.Context) *OrderDetail {
	v, err := odc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (odc *OrderDetailCreate) Exec(ctx context.Context) error {
	_, err := odc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (odc *OrderDetailCreate) ExecX(ctx context.Context) {
	if err := odc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (odc *OrderDetailCreate) check() error {
	return nil
}

func (odc *OrderDetailCreate) sqlSave(ctx context.Context) (*OrderDetail, error) {
	if err := odc.check(); err != nil {
		return nil, err
	}
	_node, _spec := odc.createSpec()
	if err := sqlgraph.CreateNode(ctx, odc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	odc.mutation.id = &_node.ID
	odc.mutation.done = true
	return _node, nil
}

func (odc *OrderDetailCreate) createSpec() (*OrderDetail, *sqlgraph.CreateSpec) {
	var (
		_node = &OrderDetail{config: odc.config}
		_spec = sqlgraph.NewCreateSpec(orderdetail.Table, sqlgraph.NewFieldSpec(orderdetail.FieldID, field.TypeInt))
	)
	if value, ok := odc.mutation.Quantity(); ok {
		_spec.SetField(orderdetail.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if value, ok := odc.mutation.ProductID(); ok {
		_spec.SetField(orderdetail.FieldProductID, field.TypeInt, value)
		_node.ProductID = value
	}
	if nodes := odc.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderdetail.OrderTable,
			Columns: []string{orderdetail.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := odc.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderdetail.ProductsTable,
			Columns: []string{orderdetail.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrderDetailCreateBulk is the builder for creating many OrderDetail entities in bulk.
type OrderDetailCreateBulk struct {
	config
	err      error
	builders []*OrderDetailCreate
}

// Save creates the OrderDetail entities in the database.
func (odcb *OrderDetailCreateBulk) Save(ctx context.Context) ([]*OrderDetail, error) {
	if odcb.err != nil {
		return nil, odcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(odcb.builders))
	nodes := make([]*OrderDetail, len(odcb.builders))
	mutators := make([]Mutator, len(odcb.builders))
	for i := range odcb.builders {
		func(i int, root context.Context) {
			builder := odcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderDetailMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, odcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, odcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, odcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (odcb *OrderDetailCreateBulk) SaveX(ctx context.Context) []*OrderDetail {
	v, err := odcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (odcb *OrderDetailCreateBulk) Exec(ctx context.Context) error {
	_, err := odcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (odcb *OrderDetailCreateBulk) ExecX(ctx context.Context) {
	if err := odcb.Exec(ctx); err != nil {
		panic(err)
	}
}
