// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"main/db/ent/order"
	"main/db/ent/orderdetail"
	"main/db/ent/predicate"
	"main/db/ent/product"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderDetailQuery is the builder for querying OrderDetail entities.
type OrderDetailQuery struct {
	config
	ctx          *QueryContext
	order        []orderdetail.OrderOption
	inters       []Interceptor
	predicates   []predicate.OrderDetail
	withOrder    *OrderQuery
	withProducts *ProductQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrderDetailQuery builder.
func (odq *OrderDetailQuery) Where(ps ...predicate.OrderDetail) *OrderDetailQuery {
	odq.predicates = append(odq.predicates, ps...)
	return odq
}

// Limit the number of records to be returned by this query.
func (odq *OrderDetailQuery) Limit(limit int) *OrderDetailQuery {
	odq.ctx.Limit = &limit
	return odq
}

// Offset to start from.
func (odq *OrderDetailQuery) Offset(offset int) *OrderDetailQuery {
	odq.ctx.Offset = &offset
	return odq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (odq *OrderDetailQuery) Unique(unique bool) *OrderDetailQuery {
	odq.ctx.Unique = &unique
	return odq
}

// Order specifies how the records should be ordered.
func (odq *OrderDetailQuery) Order(o ...orderdetail.OrderOption) *OrderDetailQuery {
	odq.order = append(odq.order, o...)
	return odq
}

// QueryOrder chains the current query on the "order" edge.
func (odq *OrderDetailQuery) QueryOrder() *OrderQuery {
	query := (&OrderClient{config: odq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := odq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := odq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orderdetail.Table, orderdetail.FieldID, selector),
			sqlgraph.To(order.Table, order.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderdetail.OrderTable, orderdetail.OrderColumn),
		)
		fromU = sqlgraph.SetNeighbors(odq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProducts chains the current query on the "products" edge.
func (odq *OrderDetailQuery) QueryProducts() *ProductQuery {
	query := (&ProductClient{config: odq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := odq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := odq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orderdetail.Table, orderdetail.FieldID, selector),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderdetail.ProductsTable, orderdetail.ProductsColumn),
		)
		fromU = sqlgraph.SetNeighbors(odq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OrderDetail entity from the query.
// Returns a *NotFoundError when no OrderDetail was found.
func (odq *OrderDetailQuery) First(ctx context.Context) (*OrderDetail, error) {
	nodes, err := odq.Limit(1).All(setContextOp(ctx, odq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{orderdetail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (odq *OrderDetailQuery) FirstX(ctx context.Context) *OrderDetail {
	node, err := odq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrderDetail ID from the query.
// Returns a *NotFoundError when no OrderDetail ID was found.
func (odq *OrderDetailQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = odq.Limit(1).IDs(setContextOp(ctx, odq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{orderdetail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (odq *OrderDetailQuery) FirstIDX(ctx context.Context) int {
	id, err := odq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrderDetail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OrderDetail entity is found.
// Returns a *NotFoundError when no OrderDetail entities are found.
func (odq *OrderDetailQuery) Only(ctx context.Context) (*OrderDetail, error) {
	nodes, err := odq.Limit(2).All(setContextOp(ctx, odq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{orderdetail.Label}
	default:
		return nil, &NotSingularError{orderdetail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (odq *OrderDetailQuery) OnlyX(ctx context.Context) *OrderDetail {
	node, err := odq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrderDetail ID in the query.
// Returns a *NotSingularError when more than one OrderDetail ID is found.
// Returns a *NotFoundError when no entities are found.
func (odq *OrderDetailQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = odq.Limit(2).IDs(setContextOp(ctx, odq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{orderdetail.Label}
	default:
		err = &NotSingularError{orderdetail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (odq *OrderDetailQuery) OnlyIDX(ctx context.Context) int {
	id, err := odq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrderDetails.
func (odq *OrderDetailQuery) All(ctx context.Context) ([]*OrderDetail, error) {
	ctx = setContextOp(ctx, odq.ctx, ent.OpQueryAll)
	if err := odq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OrderDetail, *OrderDetailQuery]()
	return withInterceptors[[]*OrderDetail](ctx, odq, qr, odq.inters)
}

// AllX is like All, but panics if an error occurs.
func (odq *OrderDetailQuery) AllX(ctx context.Context) []*OrderDetail {
	nodes, err := odq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrderDetail IDs.
func (odq *OrderDetailQuery) IDs(ctx context.Context) (ids []int, err error) {
	if odq.ctx.Unique == nil && odq.path != nil {
		odq.Unique(true)
	}
	ctx = setContextOp(ctx, odq.ctx, ent.OpQueryIDs)
	if err = odq.Select(orderdetail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (odq *OrderDetailQuery) IDsX(ctx context.Context) []int {
	ids, err := odq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (odq *OrderDetailQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, odq.ctx, ent.OpQueryCount)
	if err := odq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, odq, querierCount[*OrderDetailQuery](), odq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (odq *OrderDetailQuery) CountX(ctx context.Context) int {
	count, err := odq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (odq *OrderDetailQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, odq.ctx, ent.OpQueryExist)
	switch _, err := odq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (odq *OrderDetailQuery) ExistX(ctx context.Context) bool {
	exist, err := odq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrderDetailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (odq *OrderDetailQuery) Clone() *OrderDetailQuery {
	if odq == nil {
		return nil
	}
	return &OrderDetailQuery{
		config:       odq.config,
		ctx:          odq.ctx.Clone(),
		order:        append([]orderdetail.OrderOption{}, odq.order...),
		inters:       append([]Interceptor{}, odq.inters...),
		predicates:   append([]predicate.OrderDetail{}, odq.predicates...),
		withOrder:    odq.withOrder.Clone(),
		withProducts: odq.withProducts.Clone(),
		// clone intermediate query.
		sql:  odq.sql.Clone(),
		path: odq.path,
	}
}

// WithOrder tells the query-builder to eager-load the nodes that are connected to
// the "order" edge. The optional arguments are used to configure the query builder of the edge.
func (odq *OrderDetailQuery) WithOrder(opts ...func(*OrderQuery)) *OrderDetailQuery {
	query := (&OrderClient{config: odq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	odq.withOrder = query
	return odq
}

// WithProducts tells the query-builder to eager-load the nodes that are connected to
// the "products" edge. The optional arguments are used to configure the query builder of the edge.
func (odq *OrderDetailQuery) WithProducts(opts ...func(*ProductQuery)) *OrderDetailQuery {
	query := (&ProductClient{config: odq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	odq.withProducts = query
	return odq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Quantity int `json:"quantity,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrderDetail.Query().
//		GroupBy(orderdetail.FieldQuantity).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (odq *OrderDetailQuery) GroupBy(field string, fields ...string) *OrderDetailGroupBy {
	odq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OrderDetailGroupBy{build: odq}
	grbuild.flds = &odq.ctx.Fields
	grbuild.label = orderdetail.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Quantity int `json:"quantity,omitempty"`
//	}
//
//	client.OrderDetail.Query().
//		Select(orderdetail.FieldQuantity).
//		Scan(ctx, &v)
func (odq *OrderDetailQuery) Select(fields ...string) *OrderDetailSelect {
	odq.ctx.Fields = append(odq.ctx.Fields, fields...)
	sbuild := &OrderDetailSelect{OrderDetailQuery: odq}
	sbuild.label = orderdetail.Label
	sbuild.flds, sbuild.scan = &odq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OrderDetailSelect configured with the given aggregations.
func (odq *OrderDetailQuery) Aggregate(fns ...AggregateFunc) *OrderDetailSelect {
	return odq.Select().Aggregate(fns...)
}

func (odq *OrderDetailQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range odq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, odq); err != nil {
				return err
			}
		}
	}
	for _, f := range odq.ctx.Fields {
		if !orderdetail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if odq.path != nil {
		prev, err := odq.path(ctx)
		if err != nil {
			return err
		}
		odq.sql = prev
	}
	return nil
}

func (odq *OrderDetailQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OrderDetail, error) {
	var (
		nodes       = []*OrderDetail{}
		_spec       = odq.querySpec()
		loadedTypes = [2]bool{
			odq.withOrder != nil,
			odq.withProducts != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OrderDetail).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OrderDetail{config: odq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, odq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := odq.withOrder; query != nil {
		if err := odq.loadOrder(ctx, query, nodes, nil,
			func(n *OrderDetail, e *Order) { n.Edges.Order = e }); err != nil {
			return nil, err
		}
	}
	if query := odq.withProducts; query != nil {
		if err := odq.loadProducts(ctx, query, nodes, nil,
			func(n *OrderDetail, e *Product) { n.Edges.Products = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (odq *OrderDetailQuery) loadOrder(ctx context.Context, query *OrderQuery, nodes []*OrderDetail, init func(*OrderDetail), assign func(*OrderDetail, *Order)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*OrderDetail)
	for i := range nodes {
		fk := nodes[i].OrderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(order.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "order_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (odq *OrderDetailQuery) loadProducts(ctx context.Context, query *ProductQuery, nodes []*OrderDetail, init func(*OrderDetail), assign func(*OrderDetail, *Product)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*OrderDetail)
	for i := range nodes {
		fk := nodes[i].OrderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(product.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "order_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (odq *OrderDetailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := odq.querySpec()
	_spec.Node.Columns = odq.ctx.Fields
	if len(odq.ctx.Fields) > 0 {
		_spec.Unique = odq.ctx.Unique != nil && *odq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, odq.driver, _spec)
}

func (odq *OrderDetailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(orderdetail.Table, orderdetail.Columns, sqlgraph.NewFieldSpec(orderdetail.FieldID, field.TypeInt))
	_spec.From = odq.sql
	if unique := odq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if odq.path != nil {
		_spec.Unique = true
	}
	if fields := odq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderdetail.FieldID)
		for i := range fields {
			if fields[i] != orderdetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if odq.withOrder != nil {
			_spec.Node.AddColumnOnce(orderdetail.FieldOrderID)
		}
		if odq.withProducts != nil {
			_spec.Node.AddColumnOnce(orderdetail.FieldOrderID)
		}
	}
	if ps := odq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := odq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := odq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := odq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (odq *OrderDetailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(odq.driver.Dialect())
	t1 := builder.Table(orderdetail.Table)
	columns := odq.ctx.Fields
	if len(columns) == 0 {
		columns = orderdetail.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if odq.sql != nil {
		selector = odq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if odq.ctx.Unique != nil && *odq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range odq.predicates {
		p(selector)
	}
	for _, p := range odq.order {
		p(selector)
	}
	if offset := odq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := odq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OrderDetailGroupBy is the group-by builder for OrderDetail entities.
type OrderDetailGroupBy struct {
	selector
	build *OrderDetailQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (odgb *OrderDetailGroupBy) Aggregate(fns ...AggregateFunc) *OrderDetailGroupBy {
	odgb.fns = append(odgb.fns, fns...)
	return odgb
}

// Scan applies the selector query and scans the result into the given value.
func (odgb *OrderDetailGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, odgb.build.ctx, ent.OpQueryGroupBy)
	if err := odgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderDetailQuery, *OrderDetailGroupBy](ctx, odgb.build, odgb, odgb.build.inters, v)
}

func (odgb *OrderDetailGroupBy) sqlScan(ctx context.Context, root *OrderDetailQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(odgb.fns))
	for _, fn := range odgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*odgb.flds)+len(odgb.fns))
		for _, f := range *odgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*odgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := odgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OrderDetailSelect is the builder for selecting fields of OrderDetail entities.
type OrderDetailSelect struct {
	*OrderDetailQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ods *OrderDetailSelect) Aggregate(fns ...AggregateFunc) *OrderDetailSelect {
	ods.fns = append(ods.fns, fns...)
	return ods
}

// Scan applies the selector query and scans the result into the given value.
func (ods *OrderDetailSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ods.ctx, ent.OpQuerySelect)
	if err := ods.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderDetailQuery, *OrderDetailSelect](ctx, ods.OrderDetailQuery, ods, ods.inters, v)
}

func (ods *OrderDetailSelect) sqlScan(ctx context.Context, root *OrderDetailQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ods.fns))
	for _, fn := range ods.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ods.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ods.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
