// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"main/db/ent/predicate"
	"main/db/ent/productprice"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductPriceDelete is the builder for deleting a ProductPrice entity.
type ProductPriceDelete struct {
	config
	hooks    []Hook
	mutation *ProductPriceMutation
}

// Where appends a list predicates to the ProductPriceDelete builder.
func (ppd *ProductPriceDelete) Where(ps ...predicate.ProductPrice) *ProductPriceDelete {
	ppd.mutation.Where(ps...)
	return ppd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ppd *ProductPriceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ppd.sqlExec, ppd.mutation, ppd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ppd *ProductPriceDelete) ExecX(ctx context.Context) int {
	n, err := ppd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ppd *ProductPriceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(productprice.Table, sqlgraph.NewFieldSpec(productprice.FieldID, field.TypeInt))
	if ps := ppd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ppd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ppd.mutation.done = true
	return affected, err
}

// ProductPriceDeleteOne is the builder for deleting a single ProductPrice entity.
type ProductPriceDeleteOne struct {
	ppd *ProductPriceDelete
}

// Where appends a list predicates to the ProductPriceDelete builder.
func (ppdo *ProductPriceDeleteOne) Where(ps ...predicate.ProductPrice) *ProductPriceDeleteOne {
	ppdo.ppd.mutation.Where(ps...)
	return ppdo
}

// Exec executes the deletion query.
func (ppdo *ProductPriceDeleteOne) Exec(ctx context.Context) error {
	n, err := ppdo.ppd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productprice.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ppdo *ProductPriceDeleteOne) ExecX(ctx context.Context) {
	if err := ppdo.Exec(ctx); err != nil {
		panic(err)
	}
}
