// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/db/ent/predicate"
	"main/db/ent/user"
	"main/db/ent/usertoken"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserTokenUpdate is the builder for updating UserToken entities.
type UserTokenUpdate struct {
	config
	hooks    []Hook
	mutation *UserTokenMutation
}

// Where appends a list predicates to the UserTokenUpdate builder.
func (utu *UserTokenUpdate) Where(ps ...predicate.UserToken) *UserTokenUpdate {
	utu.mutation.Where(ps...)
	return utu
}

// SetToken sets the "token" field.
func (utu *UserTokenUpdate) SetToken(s string) *UserTokenUpdate {
	utu.mutation.SetToken(s)
	return utu
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (utu *UserTokenUpdate) SetNillableToken(s *string) *UserTokenUpdate {
	if s != nil {
		utu.SetToken(*s)
	}
	return utu
}

// ClearToken clears the value of the "token" field.
func (utu *UserTokenUpdate) ClearToken() *UserTokenUpdate {
	utu.mutation.ClearToken()
	return utu
}

// SetExpirationDate sets the "expiration_date" field.
func (utu *UserTokenUpdate) SetExpirationDate(t time.Time) *UserTokenUpdate {
	utu.mutation.SetExpirationDate(t)
	return utu
}

// SetNillableExpirationDate sets the "expiration_date" field if the given value is not nil.
func (utu *UserTokenUpdate) SetNillableExpirationDate(t *time.Time) *UserTokenUpdate {
	if t != nil {
		utu.SetExpirationDate(*t)
	}
	return utu
}

// ClearExpirationDate clears the value of the "expiration_date" field.
func (utu *UserTokenUpdate) ClearExpirationDate() *UserTokenUpdate {
	utu.mutation.ClearExpirationDate()
	return utu
}

// SetType sets the "type" field.
func (utu *UserTokenUpdate) SetType(s string) *UserTokenUpdate {
	utu.mutation.SetType(s)
	return utu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (utu *UserTokenUpdate) SetNillableType(s *string) *UserTokenUpdate {
	if s != nil {
		utu.SetType(*s)
	}
	return utu
}

// ClearType clears the value of the "type" field.
func (utu *UserTokenUpdate) ClearType() *UserTokenUpdate {
	utu.mutation.ClearType()
	return utu
}

// SetStatus sets the "status" field.
func (utu *UserTokenUpdate) SetStatus(s string) *UserTokenUpdate {
	utu.mutation.SetStatus(s)
	return utu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (utu *UserTokenUpdate) SetNillableStatus(s *string) *UserTokenUpdate {
	if s != nil {
		utu.SetStatus(*s)
	}
	return utu
}

// ClearStatus clears the value of the "status" field.
func (utu *UserTokenUpdate) ClearStatus() *UserTokenUpdate {
	utu.mutation.ClearStatus()
	return utu
}

// SetLastUsed sets the "last_used" field.
func (utu *UserTokenUpdate) SetLastUsed(s string) *UserTokenUpdate {
	utu.mutation.SetLastUsed(s)
	return utu
}

// SetNillableLastUsed sets the "last_used" field if the given value is not nil.
func (utu *UserTokenUpdate) SetNillableLastUsed(s *string) *UserTokenUpdate {
	if s != nil {
		utu.SetLastUsed(*s)
	}
	return utu
}

// ClearLastUsed clears the value of the "last_used" field.
func (utu *UserTokenUpdate) ClearLastUsed() *UserTokenUpdate {
	utu.mutation.ClearLastUsed()
	return utu
}

// SetUserID sets the "user_id" field.
func (utu *UserTokenUpdate) SetUserID(i int) *UserTokenUpdate {
	utu.mutation.SetUserID(i)
	return utu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (utu *UserTokenUpdate) SetNillableUserID(i *int) *UserTokenUpdate {
	if i != nil {
		utu.SetUserID(*i)
	}
	return utu
}

// ClearUserID clears the value of the "user_id" field.
func (utu *UserTokenUpdate) ClearUserID() *UserTokenUpdate {
	utu.mutation.ClearUserID()
	return utu
}

// SetUser sets the "user" edge to the User entity.
func (utu *UserTokenUpdate) SetUser(u *User) *UserTokenUpdate {
	return utu.SetUserID(u.ID)
}

// Mutation returns the UserTokenMutation object of the builder.
func (utu *UserTokenUpdate) Mutation() *UserTokenMutation {
	return utu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (utu *UserTokenUpdate) ClearUser() *UserTokenUpdate {
	utu.mutation.ClearUser()
	return utu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (utu *UserTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, utu.sqlSave, utu.mutation, utu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (utu *UserTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := utu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (utu *UserTokenUpdate) Exec(ctx context.Context) error {
	_, err := utu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (utu *UserTokenUpdate) ExecX(ctx context.Context) {
	if err := utu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (utu *UserTokenUpdate) check() error {
	if v, ok := utu.mutation.Token(); ok {
		if err := usertoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "UserToken.token": %w`, err)}
		}
	}
	if v, ok := utu.mutation.GetType(); ok {
		if err := usertoken.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UserToken.type": %w`, err)}
		}
	}
	if v, ok := utu.mutation.LastUsed(); ok {
		if err := usertoken.LastUsedValidator(v); err != nil {
			return &ValidationError{Name: "last_used", err: fmt.Errorf(`ent: validator failed for field "UserToken.last_used": %w`, err)}
		}
	}
	return nil
}

func (utu *UserTokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := utu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(usertoken.Table, usertoken.Columns, sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeInt))
	if ps := utu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := utu.mutation.Token(); ok {
		_spec.SetField(usertoken.FieldToken, field.TypeString, value)
	}
	if utu.mutation.TokenCleared() {
		_spec.ClearField(usertoken.FieldToken, field.TypeString)
	}
	if value, ok := utu.mutation.ExpirationDate(); ok {
		_spec.SetField(usertoken.FieldExpirationDate, field.TypeTime, value)
	}
	if utu.mutation.ExpirationDateCleared() {
		_spec.ClearField(usertoken.FieldExpirationDate, field.TypeTime)
	}
	if value, ok := utu.mutation.GetType(); ok {
		_spec.SetField(usertoken.FieldType, field.TypeString, value)
	}
	if utu.mutation.TypeCleared() {
		_spec.ClearField(usertoken.FieldType, field.TypeString)
	}
	if value, ok := utu.mutation.Status(); ok {
		_spec.SetField(usertoken.FieldStatus, field.TypeString, value)
	}
	if utu.mutation.StatusCleared() {
		_spec.ClearField(usertoken.FieldStatus, field.TypeString)
	}
	if value, ok := utu.mutation.LastUsed(); ok {
		_spec.SetField(usertoken.FieldLastUsed, field.TypeString, value)
	}
	if utu.mutation.LastUsedCleared() {
		_spec.ClearField(usertoken.FieldLastUsed, field.TypeString)
	}
	if utu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usertoken.UserTable,
			Columns: []string{usertoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := utu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usertoken.UserTable,
			Columns: []string{usertoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, utu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	utu.mutation.done = true
	return n, nil
}

// UserTokenUpdateOne is the builder for updating a single UserToken entity.
type UserTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserTokenMutation
}

// SetToken sets the "token" field.
func (utuo *UserTokenUpdateOne) SetToken(s string) *UserTokenUpdateOne {
	utuo.mutation.SetToken(s)
	return utuo
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (utuo *UserTokenUpdateOne) SetNillableToken(s *string) *UserTokenUpdateOne {
	if s != nil {
		utuo.SetToken(*s)
	}
	return utuo
}

// ClearToken clears the value of the "token" field.
func (utuo *UserTokenUpdateOne) ClearToken() *UserTokenUpdateOne {
	utuo.mutation.ClearToken()
	return utuo
}

// SetExpirationDate sets the "expiration_date" field.
func (utuo *UserTokenUpdateOne) SetExpirationDate(t time.Time) *UserTokenUpdateOne {
	utuo.mutation.SetExpirationDate(t)
	return utuo
}

// SetNillableExpirationDate sets the "expiration_date" field if the given value is not nil.
func (utuo *UserTokenUpdateOne) SetNillableExpirationDate(t *time.Time) *UserTokenUpdateOne {
	if t != nil {
		utuo.SetExpirationDate(*t)
	}
	return utuo
}

// ClearExpirationDate clears the value of the "expiration_date" field.
func (utuo *UserTokenUpdateOne) ClearExpirationDate() *UserTokenUpdateOne {
	utuo.mutation.ClearExpirationDate()
	return utuo
}

// SetType sets the "type" field.
func (utuo *UserTokenUpdateOne) SetType(s string) *UserTokenUpdateOne {
	utuo.mutation.SetType(s)
	return utuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (utuo *UserTokenUpdateOne) SetNillableType(s *string) *UserTokenUpdateOne {
	if s != nil {
		utuo.SetType(*s)
	}
	return utuo
}

// ClearType clears the value of the "type" field.
func (utuo *UserTokenUpdateOne) ClearType() *UserTokenUpdateOne {
	utuo.mutation.ClearType()
	return utuo
}

// SetStatus sets the "status" field.
func (utuo *UserTokenUpdateOne) SetStatus(s string) *UserTokenUpdateOne {
	utuo.mutation.SetStatus(s)
	return utuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (utuo *UserTokenUpdateOne) SetNillableStatus(s *string) *UserTokenUpdateOne {
	if s != nil {
		utuo.SetStatus(*s)
	}
	return utuo
}

// ClearStatus clears the value of the "status" field.
func (utuo *UserTokenUpdateOne) ClearStatus() *UserTokenUpdateOne {
	utuo.mutation.ClearStatus()
	return utuo
}

// SetLastUsed sets the "last_used" field.
func (utuo *UserTokenUpdateOne) SetLastUsed(s string) *UserTokenUpdateOne {
	utuo.mutation.SetLastUsed(s)
	return utuo
}

// SetNillableLastUsed sets the "last_used" field if the given value is not nil.
func (utuo *UserTokenUpdateOne) SetNillableLastUsed(s *string) *UserTokenUpdateOne {
	if s != nil {
		utuo.SetLastUsed(*s)
	}
	return utuo
}

// ClearLastUsed clears the value of the "last_used" field.
func (utuo *UserTokenUpdateOne) ClearLastUsed() *UserTokenUpdateOne {
	utuo.mutation.ClearLastUsed()
	return utuo
}

// SetUserID sets the "user_id" field.
func (utuo *UserTokenUpdateOne) SetUserID(i int) *UserTokenUpdateOne {
	utuo.mutation.SetUserID(i)
	return utuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (utuo *UserTokenUpdateOne) SetNillableUserID(i *int) *UserTokenUpdateOne {
	if i != nil {
		utuo.SetUserID(*i)
	}
	return utuo
}

// ClearUserID clears the value of the "user_id" field.
func (utuo *UserTokenUpdateOne) ClearUserID() *UserTokenUpdateOne {
	utuo.mutation.ClearUserID()
	return utuo
}

// SetUser sets the "user" edge to the User entity.
func (utuo *UserTokenUpdateOne) SetUser(u *User) *UserTokenUpdateOne {
	return utuo.SetUserID(u.ID)
}

// Mutation returns the UserTokenMutation object of the builder.
func (utuo *UserTokenUpdateOne) Mutation() *UserTokenMutation {
	return utuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (utuo *UserTokenUpdateOne) ClearUser() *UserTokenUpdateOne {
	utuo.mutation.ClearUser()
	return utuo
}

// Where appends a list predicates to the UserTokenUpdate builder.
func (utuo *UserTokenUpdateOne) Where(ps ...predicate.UserToken) *UserTokenUpdateOne {
	utuo.mutation.Where(ps...)
	return utuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (utuo *UserTokenUpdateOne) Select(field string, fields ...string) *UserTokenUpdateOne {
	utuo.fields = append([]string{field}, fields...)
	return utuo
}

// Save executes the query and returns the updated UserToken entity.
func (utuo *UserTokenUpdateOne) Save(ctx context.Context) (*UserToken, error) {
	return withHooks(ctx, utuo.sqlSave, utuo.mutation, utuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (utuo *UserTokenUpdateOne) SaveX(ctx context.Context) *UserToken {
	node, err := utuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (utuo *UserTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := utuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (utuo *UserTokenUpdateOne) ExecX(ctx context.Context) {
	if err := utuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (utuo *UserTokenUpdateOne) check() error {
	if v, ok := utuo.mutation.Token(); ok {
		if err := usertoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "UserToken.token": %w`, err)}
		}
	}
	if v, ok := utuo.mutation.GetType(); ok {
		if err := usertoken.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UserToken.type": %w`, err)}
		}
	}
	if v, ok := utuo.mutation.LastUsed(); ok {
		if err := usertoken.LastUsedValidator(v); err != nil {
			return &ValidationError{Name: "last_used", err: fmt.Errorf(`ent: validator failed for field "UserToken.last_used": %w`, err)}
		}
	}
	return nil
}

func (utuo *UserTokenUpdateOne) sqlSave(ctx context.Context) (_node *UserToken, err error) {
	if err := utuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usertoken.Table, usertoken.Columns, sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeInt))
	id, ok := utuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := utuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usertoken.FieldID)
		for _, f := range fields {
			if !usertoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usertoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := utuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := utuo.mutation.Token(); ok {
		_spec.SetField(usertoken.FieldToken, field.TypeString, value)
	}
	if utuo.mutation.TokenCleared() {
		_spec.ClearField(usertoken.FieldToken, field.TypeString)
	}
	if value, ok := utuo.mutation.ExpirationDate(); ok {
		_spec.SetField(usertoken.FieldExpirationDate, field.TypeTime, value)
	}
	if utuo.mutation.ExpirationDateCleared() {
		_spec.ClearField(usertoken.FieldExpirationDate, field.TypeTime)
	}
	if value, ok := utuo.mutation.GetType(); ok {
		_spec.SetField(usertoken.FieldType, field.TypeString, value)
	}
	if utuo.mutation.TypeCleared() {
		_spec.ClearField(usertoken.FieldType, field.TypeString)
	}
	if value, ok := utuo.mutation.Status(); ok {
		_spec.SetField(usertoken.FieldStatus, field.TypeString, value)
	}
	if utuo.mutation.StatusCleared() {
		_spec.ClearField(usertoken.FieldStatus, field.TypeString)
	}
	if value, ok := utuo.mutation.LastUsed(); ok {
		_spec.SetField(usertoken.FieldLastUsed, field.TypeString, value)
	}
	if utuo.mutation.LastUsedCleared() {
		_spec.ClearField(usertoken.FieldLastUsed, field.TypeString)
	}
	if utuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usertoken.UserTable,
			Columns: []string{usertoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := utuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usertoken.UserTable,
			Columns: []string{usertoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserToken{config: utuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, utuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	utuo.mutation.done = true
	return _node, nil
}
